elo:
  outputs:

    dev:
      type: postgres
      threads: 10
      host: localhost
      port: 5432
      user: postgres
      pass: '7751'
      dbname: elo
      schema: public

    prod:
      type: postgres
      threads: 10
      host: localhost
      port: 5432
      user: postgres
      pass: '7751'
      dbname: ELO
      schema: public

  target: dev
